version: '3.0'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: todo_list
    volumes:
      - ./data/mysql:/var/lib/mysql
  app:
    build:
      context: .
    image: go-todo-list:latest
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: my-secret-pw
      DB_NAME: todo_list
      DB_PORT: 3306
      DB_HOST: db
    links:
      - "db:localhost"
    ports:
      - "8080:8080"

